# Generated by Django 5.0.6 on 2024-06-21 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exercise_category_alter_food_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
