# Generated by Django 5.0.6 on 2024-06-23 09:34

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='date',
            field=models.DateField(default=tracker.models.current_date),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='date',
            field=models.DateField(default=tracker.models.current_date),
        ),
    ]
