# Generated by Django 5.0.6 on 2024-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userfood_quantity_alter_food_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('high protein', 'High Protein'), ('low fat', 'Low Fat'), ('low carbs', 'Low Carbs'), ('gluten free', 'Gluten Free'), ('high fibre', 'High Fibre')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
